Merge login with current code
emilymarkova/C4GProject pull request #3
Opened 2024-07-02 23:16 UTC by emilymarkova

2024-07-02 23:37 UTC, bigalex2k commented on src/pages/Home.tsx
I'm pretty sure on line 4, it mentions importing Background from '../Components/Background'. However, Backround is not there.

2024-07-02 23:40 UTC, bigalex2k commented on src/assets/login_background.png
My background image was probably deleted. I don't see it here.

2024-07-02 23:42 UTC, bigalex2k commented on src/Components/PageContent.tsx
The entire inside this file is gone. Here's what's supposed to be here
<>
    <div className="TitleContent">
        A calender specialized in education
    </div>
    <div className="TitleContent2">
        [Insert name] is a calendar that focuses on its 
        <br>
        </br>
        impact on student’s education.
    </div>
    </>

2024-07-02 23:43 UTC, bigalex2k commented on src/App.tsx
I"m pretty sure there was supposed to be an App.css file in the src folder somewhere, but I don't see it.

2024-07-02 23:47 UTC, bigalex2k requested changes
1. My App.css file stored in the src file is gone
2. My PageContent.tsx file has had it's inside ripped out. It's currently an empty function.
3. My Background.txs file was deleted and the background picture for the home page was deleted.

I think that's it. I think the code and files for this should be stored within the history of this repository if you need it.

2024-07-03 00:02 UTC, emilymarkova commented
1. Not 100% sure but I think the commit might only show what I'm changing so App.css might not be showing up as a file that's part of the commit because I didn't change it.
2. I just took a look at PageContent.tsx, and it seems to be empty at first glance, but if you expand the file (press Edit or View), it seems that the content is still there.
3. ^Same as 1 - I think I just didn't change Background.txs and the background image so that's why they didn't show up on the commit?

2024-07-03 01:14 UTC, bigalex2k commented
I think you're right. my bad.

2024-07-03 01:15 UTC, bigalex2k approved these changes

2024-07-03 01:23 UTC, merged